# Generated by Django 4.2.4 on 2023-08-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
